project_id = "fxnnnhmhshmhcttmucwf"

[functions.send-campaign-emails]
verify_jwt = true

[functions.find-company-emails]
verify_jwt = true

[functions.search-companies]
verify_jwt = true

[functions.scrape-websites]
verify_jwt = true

[functions.france-travail]
verify_jwt = false

[functions.create-gmail-drafts]
verify_jwt = true