project_id = "fxnnnhmhshmhcttmucwf"

[functions.send-campaign-emails]
verify_jwt = true

[functions.find-company-emails]
verify_jwt = true

[functions.search-companies]
verify_jwt = true

[functions.scrape-websites]
verify_jwt = true

[functions.france-travail]
verify_jwt = true

[functions.create-gmail-drafts]
verify_jwt = true

[functions.send-gmail-emails]
verify_jwt = true

[functions.store-gmail-tokens]
verify_jwt = true

[functions.refresh-gmail-token]
verify_jwt = true

[functions.gmail-oauth-callback]
verify_jwt = true

[functions.gmail-oauth-config]
verify_jwt = false